### ISSUE TITLE
Accordion not working in dist generated file

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-accordion-v2-changelog#1]
Hy, the Accordion is not working if i use the dist generated css file using npm run gulp dist.

This is my gulp script

function purgeCSS() {
    return new Promise(function (resolve, reject) {
        var stream = gulp.src(cssFolder + '/style.min.css')
            .pipe(purgecss({
                content: ['**/**/*.htm', scriptsJsPath + '/scripts.js'],
                safelist: {
                    standard: ['.is-hidden', '.is-visible'],
                    deep: [/class$/],
                    greedy: []
                },
                defaultExtractor: content => content.match(/[\w-/:%@]+(?<!:)/g) || []
            }))
            .pipe(gulp.dest(distFolder + '/css'));

        stream.on('finish', function () {
            resolve();
        });
    });
};

can you please have a look on it? Thank you

**Comment by dariopetraroia** [comment]
Sorry it was a cache problem

**Comment by claudia-romano** [comment]
Hi Dario, I just tested it on my side and everything seems to be working fine. 
Are you having style issues or issue with the behaviour (not opening/closing)? Thanks

**Comment by dariopetraroia** [comment]
Hy Claudia with the behaviour (not opening/closing)

Thanks

Dario

**Comment by claudia-romano** [comment]
Hi Dario, unfortunately I cannot reproduce the bug. Could you please provide more info? For example, is the class `accordion-v2__item--is-open` added to the accordion element? 

Also, if you are using CodyFrame v3, could you please check where your PurgeCSS comments are in the .scss files? Thanks

**Comment by dariopetraroia** [comment]
Hy Claudia,

yes the javascript adds the accordion-v2__item--is-open class but the class is missing in the css file i generate with the purgeCSS function.

This is my package.json

{
    "name": "automix",
    "version": "0.0.1",
    "scripts": {
        "gulp": "gulp",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "devDependencies": {
        "autoprefixer": "^9.4.3",
        "browser-sync": "^2.26.3",
        "codyhouse-framework": "^3.0.4",
        "gulp": "^4.0.0",
        "gulp-clean-css": "^4.3.0",
        "gulp-concat": "^2.6.1",
        "gulp-postcss": "^8.0.0",
        "gulp-purgecss": "^3.0.0",
        "gulp-rename": "^1.4.0",
        "gulp-sass": "^4.1.1",
        "gulp-sass-glob": "git+https://github.com/CodyHouse/gulp-sass-glob.git",
        "gulp-uglify": "^3.0.2",
        "postcss-calc": "^7.0.1",
        "postcss-css-variables": "git+https://github.com/CodyHouse/postcss-css-variables.git",
        "sass": "^1.49.7",
        "sass-embedded": "1.0.0-beta.3"
    },
    "dependencies": {}
}

**Comment by claudia-romano** [comment]
Hi Dario, could you check where your purgeCSS start comment is? It should be at the end of the _custom-style.scss file:
https://capture.dropbox.com/AO5z8Ru5K0oNrkPA?src=ss

Thanks!

**Comment by dariopetraroia** [comment]
Hy Claudia, thank you so mutch the purgeCSS comment was missing may be I had an old version of _custom-style.scss

Thank you!!
